### ISSUE TITLE
errors should respect Accept header

### ISSUE THREAD

**Issue by giuliopaci** [telefonicaid/fiware-keystone-scim#16]
When I issue this command, requesting a resource id with spaces in it, ```curl http://localhost:35357/v3/OS-SCIM/Users/"name with spaces" -H "X-Auth-Token: valid_token" -H "Content-Type: application/json" -H "Accept: application/json"```, I get the following HTML content describing the error, instead of the typical Json format:
```
<head>
<title>Error response</title>
</head>
<body>
<h1>Error response</h1>
<p>Error code 400.
<p>Message: Bad request syntax ('GET /v3/OS-SCIM/Users/name with spaces HTTP/1.1').
<p>Error code explanation: 400 = Bad request syntax or unsupported method.
</body>
```

**Comment by AlvaroVega** [comment]
It seems something inherent to Keystone, not just to hist keystone-scim extension since another keystone request has the same behavior: curl http://localhost:5000/v3/domains/"name a"  -H "X-Auth-Token: valid_token" -H "Content-Type: application/json" -H "Accept: application/json"
<head>
<title>Error response</title>
</head>
<body>
<h1>Error response</h1>
<p>Error code 400.
<p>Message: Bad request syntax ('GET /v3/domains/name a HTTP/1.1').
<p>Error code explanation: 400 = Bad request syntax or unsupported method.
</body>

**Comment by giuliopaci** [comment]
Ok, I will forward the issue than.
Il 12/mag/2015 08:19, "Alvaro Vega" <notifications@github.com> ha scritto:
